### PR TITLE
Adding a Workflow for greetings to new issue 

### LINKED ISSUE #16: [FEATURE] Adding a Workflow for greetings to new issue and PRs
This workflow runs whenever a new issue or pull request is opened.
Greet User: It uses the actions-ecosystem/action-create-comment action to post a customized comment directly on the issue or pull request.
Personalized Message: The message greets the user by username and dynamically adjusts based on whether it’s an issue or pull request. It also includes a link to the contribution guidelines for new contributors.
**Benefits of the Greeting Workflow**
- Improves User Experience
- Encourages Quality Contributions
- Reduces Common Questions

### PR DESCRIPTION
**Pull request by aditiverma-21**
## 📋 Description
This workflow runs whenever a new issue or pull request is opened.
Greet User: It uses the actions-ecosystem/action-create-comment action to post a customized comment directly on the issue or pull request.
Personalized Message: The message greets the user by username and dynamically adjusts based on whether it’s an issue or pull request. It also includes a link to the contribution guidelines for new contributors.

Fixes #16 

## 🚨 Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
Thank you for your contribution @aditiverma-21

**Comment by aditiverma-21** [comment]
Please add labels.

**Comment by aditiverma-21** [comment]
Please add level label

**Comment by yashksaini-coder** [comment]
> Please add level label and gssoc ext label

Please refer to this #19

**Comment by aditiverma-21** [comment]
Okay Thank you 
and sorry for the misunderstanding.

**Comment by yashksaini-coder** [comment]
> Okay Thank you and sorry for the misunderstanding.

No problem.

**Pull request merged**
